### ISSUE TITLE
Lekce 1: Deklarace a definice proměnných bublaniny najednou

### ISSUE THREAD

**Issue by ondrakucera** [czechitas/java-1#18]
Nevím, jak moc to chceme řešit, protože je to kus kódu, který v tu chvíli účastnice ještě asi ani nevnímají jako něco, na co by měly koukat nebo se tomu snažit rozumět, a svůj kód píšou až pod to, ale obecně se na prvních hodinách dlouhodobě všichni (co vím) snažíme oddělovat deklaraci proměnné od přiřazení první hodnoty. Nicméně v bublanině samotné tam máme celý ten vrchní blok řádků jako `Miska cervenaMiska = new Miska("cervenaMiska");`, kde je to celé najednou. Přemýšlím, jestli by nedávalo smysl i v této ukázce to rozdělit na dva řádky, jako se o to snažíme všude jinde. Nicméně sám se neumím rozhodnout, jestli to je, nebo není dobrej nápad.

* Výhoda: větší konzistence se zbytkem výkladu.
* Nevýhoda: ta úvodní sekce bude mít rázem dvojnásobný počet řádků a bude strašně dlouhá.

**Comment by shinedeveloper** [comment]
V tomhle se klidne necham premluvit. Ja jsem ten horni blok napsal dohromady hlavne kvuli tomu, aby to nezabiralo celou obrazovku.

**Comment by ondrakucera** [comment]
Já jsem si myslel, žes to asi udělal vědomě. Jak je (snad) vidět, já sám si nejsem jistej, co je ve výsledku lepší. Pokud Ti to nevadí, tak bych navrhoval tohle tu nechat i déle otevřené, aby se k tomu případně vyjádřili i další (což může chvíli trvat, než si toho někdo všimne). :-) Pokud by většina byla nakonec pro změnu, tak PR pak udělám sám, ale zatím jak to tak chápu, tak jsme dva s názorem, že obě řešení jsou možná.

**Comment by shinedeveloper** [comment]
Tak jsem to predelal na navrhovane reseni. Je to asi jedno, ale takhle je to vice konsistentni se zbytkem materialu.
