### ISSUE TITLE
Lekce01: miska nepřebírá správně obsah druhé misky

### ISSUE THREAD

**Issue by ondrakucera** [czechitas/java-1#3]
Poznámka: tohle issue zakládám mimo jiné proto, abychom si vzájemně vůbec vyzkoušeli práci s hlášením chyb. :-)

Jedna účastnice narazila na následující problém. Vajíčka, cukr a máslo dala do červené misky. Mouku si odvážila na žluté misce. Následně do žluté misky přihodila prášek do pečiva. Poté to žluté misky hodila celý obsah červené misky. Výsledně jí to hlásilo, že těsto nemá máslo. Miska.nalozObsahMisky totiž máslo nezpracovává.

Mimochodem jestli se dobře dívám, tak prášek do pečiva se při nalozObsahMisky taky nezpracovává.

**Comment by shinedeveloper** [comment]
Podobne jeste ovoce.

Ted uz by to tedy melo byt opravene.
