### ISSUE TITLE
Lekce02: Spustitelný JAR činí potíže při nahrávání na Google Drive

### ISSUE THREAD

**Issue by ondrakucera** [czechitas/java-1#4]
V některých projektech historicky zůstala struktura adresáře "dist", který se plní při "build artifacts". Mimo jiné tam vzniká aplikace.jar (resp. je tam tak už na začátku předpřipraven). Bohužel si o tomhle souboru, bez ohledu na to, co v něm je, Google Drive myslí, že je zavirovaný. Když pak účastnice vyjdou z tohoto projektu pro domácí úkol a pokoušejí se to odevzdat, Drive se začne chovat velmi podivně a napředvídatelně. Někdy to řešení nahraje, někdy ho ani nenahraje (ale zároveň pro nahrávatele se tváří, že se to povedlo, takže ten ho tam vidí, ale nikdo jiný ne), a dokonce v případě, že tam řešení skutečně nahraje, po několika hodinách (nejpozději v řádu dní) ho smaže ...

Jestli si správně pamatuju, jak jsme se o tomhle buildu do spustitelného JARu bavili, ono to stejně nefungovalo úplně tak, jak sis to představoval, a ze šablony pro nové projekty jsi to odstraňoval. Chtělo by to teď ještě projít, kde to zůstalo ve stávajících projektech a odstranit to i z nich.

**Comment by shinedeveloper** [comment]
Melo by to byt vsude dusledne vycistene a smazane.
